import { supabase } from "../lib/supabaseClient";

// Items data
const itemsData = [
  {
    name: "Mask of Masquerade",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: -2,
      CRT: 0,
      CDM: 0,
      INT: 5,
      MAG: -1,
      RES: 0,
      INS: 0,
    },
    effect:
      "Deceitful Performance: Increase all allied's Atk, except self, by one third of self's INT (round up).",
  },
  {
    name: "Commander Cape",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 3,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "The Battlefield Is My Stage: Increase all allied character CRT by INT multiplied by 2.",
  },
  {
    name: "Sword",
    type: "Equipment",
    slot: "Sub",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 2,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Fire",
    type: "Magic",
    slot: "Sub",
    requirements: "4 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Blaze: Deal 1.5*MAG damage to one character (round down)",
  },
  {
    name: "Torturous Glove",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 3,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Headache: At the start of each phrase, increase equipped character's INS by 1. Psychic Piercing (3E): Deal 4 Spirit Damage to one character, then increase opponent charcater's INS by 1.",
  },
  {
    name: "Murloc Bracelet",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: -10,
      INS: 0,
    },
    effect:
      "Hot Hand, Hot Mind: Increase MAG damage received by 1, decrease PHY damage received by 1.",
  },
  {
    name: "Revolver",
    type: "Equipment",
    slot: "",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 2,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Curse",
    type: "Spirit",
    slot: "Sub",
    requirements: "8 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Lingering Resentment: Deal 6 Spirit Damage to one character, increase self's INS by 1.",
  },
  {
    name: "Nightmarish Pen",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 3,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Illusional Reality: At the end of the phrase, increase every characters' INS by 1.",
  },
  {
    name: "Peek a Boo!",
    type: "Magic",
    slot: "Main",
    requirements: "13 INT, 4E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Death's Incarnate: Increase all opponent active's INS by 3 and inactive's INS by 2.",
  },
  {
    name: "Wanderer Suit",
    type: "Equipment",
    slot: "Sub",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 1,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 10,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Denial",
    type: "Spirit",
    slot: "",
    requirements: "6 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Cancel: Deal 3 Spirit Damage to one character, then increase opponent's INS by 1.",
  },
  {
    name: "Divine Restore",
    type: "Magic",
    slot: "Main",
    requirements: "10 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Restore: Recover a total of 2.5*MAG HP, distributed evenly between all allied character (Round up).",
  },
  {
    name: "Wish",
    type: "Magic",
    slot: "Main",
    requirements: "16 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 4,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Special - Miracle Manifestation: The following effects take place\n+Rejuvation: Draw 1 card.\n+Restore: Restore one kind of used Action.\n+Reanimate: Increase ATK, DEF, INT, MAG by 1 and RES by 10 to all allied characters for this phrase.\n+Recover: Recover MAG HP to all allied character",
  },
  {
    name: "Ring of Intelligence",
    type: "Equipment",
    slot: "",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Magic Missle",
    type: "Magic",
    slot: "Sub",
    requirements: "6 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Explode: Deal 3*MAG damage to one character.",
  },
  {
    name: "Moon Sword",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 75,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Moonlight: Decrease opponent active's DEF by 1.",
  },
  {
    name: "Swordman Robe",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 2,
      DEF: 2,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Comfortable: Increase CRT by 10 and CDM by 30",
  },
  {
    name: "Heal",
    type: "Magic",
    slot: "Sub",
    requirements: "2 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Instant Recover: Recover 2 HP to self",
  },
  {
    name: "Glasses",
    type: "Equipment",
    slot: "",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 5,
      CDM: 50,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Commander Robe",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 2,
      RES: 20,
      INS: 0,
    },
    effect:
      "Behold! My Troop!: Increase all allied MAG by one fourth of INT (round down)",
  },
  {
    name: "Spirit Descent",
    type: "Magic",
    slot: "Main",
    requirements: "5 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Tremble! O Pitiful Mortal!: Deal MAG damage, then reuse self's Special (if exist).",
  },
  {
    name: "Spirit Thunder",
    type: "Magic",
    slot: "Main",
    requirements: "9 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Zap: Deal 1.5*MAG damage to one opponent's active (round down), then deal 1*MAG damage to all opponent's inactive.",
  },
  {
    name: "Spirit Fire",
    type: "Magic",
    slot: "Main",
    requirements: "6 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Burn: Deal 2.25*MAG damage (round down) to one character.",
  },
  {
    name: "Frost Earrings",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 2,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 20,
      INS: 0,
    },
    effect:
      "Frosty Aura: When self's INS is 0, increase DEF and RES by 2 and 20, respectively.",
  },
  {
    name: "Book of Law",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 5,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Judgement (2E): Deal INT / 2 + MAG / 2 (round down) MAG damage to one character.",
  },
  {
    name: "Ring of Magic",
    type: "Equipment",
    slot: "Sub",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 2,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Ice Spear",
    type: "Spirit",
    slot: "Sub",
    requirements: "6 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Frozen to the Core: Deal 4 Spirit Damage to one character, then reduce self INS by 1",
  },
  {
    name: "Pendulum",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Divination: Increase 2 HP per each HP recovery",
  },
  {
    name: "Paper Figurine Substitute",
    type: "Magic",
    slot: "Sub",
    requirements: "8 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Substitute: Grant to all allied a Paper Figurine. Paper Figurine: Until the end of this phrase, negate up to self's 1.5*MAG (round up) Spirit Damage.",
  },
  {
    name: "Illusion Creation",
    type: "Magic",
    slot: "Main",
    requirements: "4 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Illusion: Increase all allied's DEF and RES by 2 and 20 for this phrase.",
  },
  {
    name: "Air Bullet",
    type: "Magic",
    slot: "Sub",
    requirements: "8 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Pierce: Deal 4 Spirit Damage to one character, then reduce that opponent's DEF by 1 for this phrase",
  },
  {
    name: "Mechanical Arm",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 10,
      CDM: 50,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Automate: For each equipped item except this item, increase ATK by 1.",
  },
  {
    name: "Hidden Sword",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 3,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Special - Surprise Attack (2E): Perform a normal attack with CRT increased by 20, this attack is considered a Normal Attack, this can only used on active character.",
  },
  {
    name: "Metal Wings",
    type: "Equipment",
    slot: "",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 2,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Sniper Rifle",
    type: "Equipment",
    slot: "Sub",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 1,
      DEF: 0,
      CRT: 5,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Blazing Haze Sword",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 2,
      RES: 20,
      INS: 0,
    },
    effect:
      "Heat Haze (3E): Decrease all opponent's RES by 30 for this phrase Spell Assist: Reduce spell cost by 2 INT.",
  },
  {
    name: "Escape",
    type: "Magic",
    slot: "Sub",
    requirements: "8 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Escape: Increase self's RES by 60 for this phrase",
  },
  {
    name: "Abyssal Magic",
    type: "Magic",
    slot: "Main",
    requirements: "10 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Abyss: Choose one of the three following effect for this phrase.\n+Red: Fixed all characters's DEF to 20.\n+Blue: Fixed all characters's RES to 100.\n+Purple: Fixed all characters's INS to 0.",
  },
  {
    name: "Magic Vortex",
    type: "Magic",
    slot: "Sub",
    requirements: "8 INT, 3E",
    stats: {
      HP: 0,
      ATK: -1,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Magic Vortex: Last for 2 phrase, at the start of each phrase, deal 1*MAG to all opponent's active and 0.5*MAG to all opponent's inactive (round down).",
  },
  {
    name: "Alchemy Set",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Potion Maker (2E): Recover INT/3 (round up) HP to allied's active character",
  },
  {
    name: "Historical Summon",
    type: "Magic",
    slot: "Main",
    requirements: "12 INT, 4E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 4,
      MAG: 0,
      RES: 0,
      INS: 1,
    },
    effect: "Past Hologram: Search self's discarded deck and take 1 card.",
  },
  {
    name: "Foul Gold",
    type: "Equipment",
    slot: "",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 3,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "History Blast",
    type: "Magic",
    slot: "Sub",
    requirements: "14 INT, 4E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: -25,
      INT: 0,
      MAG: 2,
      RES: 0,
      INS: 0,
    },
    effect:
      "Strike to the History: Deal 2.5*MAG damage while ignoring all opponent's RES.",
  },
  {
    name: "Boreas Death Scythe",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: -5,
      ATK: 4,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: -1,
      RES: 0,
      INS: 0,
    },
    effect:
      "Dance of Death: After performing a Normal Attack, target's DEF and RES are decreased by 1 and 10 respectively for the next phrase.",
  },
  {
    name: "Red Cloak",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 25,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "A Flash of Red: When dealing a crit, decrease target's DEF by 2 for next phrase.",
  },
  {
    name: "Dancing Death",
    type: "Magic",
    slot: "Sub",
    requirements: "5 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Dancing Death: Deal 1.5*MAG damage to one character, next phrase, target's RES is decreased by 30.",
  },
  {
    name: "Heightened Sense",
    type: "Magic",
    slot: "Sub",
    requirements: "6 INT, 1E",
    stats: {
      HP: 0,
      ATK: -1,
      DEF: 0,
      CRT: 25,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Weak Point Detection: For the next phrase, all opponent characters' DEF and RES are decreased by 2 and 20 respectively.",
  },
  {
    name: "Staff of the Depth",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Corruption from Inside: When any opponent's RES is lower than 10, increase self's MAG by 1 each 10 RES below 10.",
  },
  {
    name: "Art of Corrosion",
    type: "Magic",
    slot: "Main",
    requirements: "4 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Blessing of the Depth: Opponent's active's RES is decreased by 10",
  },
  {
    name: "Corrosion Water",
    type: "Magic",
    slot: "Sub",
    requirements: "4 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: -5,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Corrosion of the Depth: Deal 1.5*MAG damage to one character, then decrease opponent's RES by 40",
  },
  {
    name: "Mind's Pollution",
    type: "Equipment",
    slot: "Sub",
    requirements: "10 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 4,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Darkness that Encroach the Mind: When performing a normal attack, increase opponent's active INS by 1.",
  },
  {
    name: "Tarot Card - Visionary",
    type: "Equipment",
    slot: "Main",
    requirements: "8 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 2,
    },
    effect:
      "Envision - Encumber: This item can be the only item a character equip and treated as having equipped 2 item card, any prior equipped items will be destroyed. Envision - Envisioning: All resources requirements, such as Energy, Special Resources, INT, etc, for any Action on this character are reduced by 1. Once per phrase, any resources or condition for an Action is unconditionally fullfilled.",
  },
  {
    name: "Rightful Inheritor - Mountain of Gold",
    type: "Equipment",
    slot: "Main",
    requirements: "10 INT, 4E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Sea of Subconsciousness - Depth of Mind",
    type: "Spirit",
    slot: "Sub",
    requirements: "10 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 1,
    },
    effect:
      "Seed of Doubt: At the start of each phrase, increase all characters' INS by 1 for 3 phrase, starting from next phrase",
  },
  {
    name: "Another World - Another Illusion",
    type: "Spirit",
    slot: "Sub",
    requirements: "8 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Paranoia: Choose a character, from the next phrase, at the start of each phrases, for 3 phrases, that character's DEF and RES will increase by 1 and 10 respectively while INS is increased by 1.",
  },
  {
    name: "Ancient Book",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Mind Control: CRT is reduced by 100, ATK is increased by 5.",
  },
  {
    name: "Mastered Clean Up",
    type: "Magic",
    slot: "Main",
    requirements: "6 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Art of Cleaning: Recover all allies' HP by 2 for each INS of the total amount of allied character's INS.",
  },
  {
    name: "Mind Maze",
    type: "Magic",
    slot: "Main",
    requirements: "8 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Maze of Mind: Deal 6 Spirit Damage to one character",
  },
  {
    name: "Tunnel of Darkness",
    type: "Magic",
    slot: "Sub",
    requirements: "10 INT, 4E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Sightless: Deal 6 Spirit Damage to one character's and 2 Spirit Damage to all opponent's inactive",
  },
  {
    name: "Armour of Beginning",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 10,
      ATK: 0,
      DEF: 2,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Dawn: When taken damage, increase self's DEF by 2 for the next phrase.",
  },
  {
    name: "Hammer of End",
    type: "Equipment",
    slot: "Main",
    requirements: "",
    stats: {
      HP: 10,
      ATK: 2,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Twilight: When taken damage, increase self's ATK by 2 for the next phrase.",
  },
  {
    name: "Shield of Zenith",
    type: "Equipment",
    slot: "Sub",
    requirements: "",
    stats: {
      HP: 5,
      ATK: 0,
      DEF: 1,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Sword of Progression",
    type: "Equipment",
    slot: "Sub",
    requirements: "",
    stats: {
      HP: 5,
      ATK: 1,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "",
  },
  {
    name: "Hour Hand of White",
    type: "Equipment",
    slot: "",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 30,
      INS: 0,
    },
    effect:
      "Verdict - Restriction: When self's casting a Magic Spell, discard a card to keep the Magic Card rather than disposing it.",
  },
  {
    name: "Minute Hand of Black",
    type: "Equipment",
    slot: "",
    requirements: "",
    stats: {
      HP: 15,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Distort - Amplification: When self's casting a Magic Spell, self's HP is decreased by 3 while self's MAG is increased by 3.",
  },
  {
    name: "Dream Invasion",
    type: "Magic",
    slot: "Main",
    requirements: "10 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Somnokinesis: Decrease opponent's active's ATK and MAG by 2 for this phrase.",
  },
  {
    name: "Guided Dream",
    type: "Magic",
    slot: "Sub",
    requirements: "10 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Promised Land: Deal 2*MAG damage to one character.",
  },
  {
    name: "Transparent Dress",
    type: "Equipment",
    slot: "",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 20,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Bewitchment (0E): Increase one character's INS by 1.",
  },
  {
    name: "Chilled Wave",
    type: "Spirit",
    slot: "",
    requirements: "4 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Deal 5 Spirit Damage to one character",
  },
  {
    name: "Haunted Velvet",
    type: "Spirit",
    slot: "",
    requirements: "6 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: -50,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Deal 3 Spirit Damage to one character and increase that character's INS by 1.",
  },
  {
    name: "Silk Cocoon",
    type: "Magic",
    slot: "",
    requirements: "2 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Recover 5 HP for each INS that an opponent's active has, then remove that opponnet's INS.",
  },
  {
    name: "Pistol of Light",
    type: "Equipment",
    slot: "",
    requirements: "",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Bullet of Light (4E): Deal MAG damage to one opponent's active's character and 0.5*MAG damage to that opponent's inactive (round down)",
  },
  {
    name: "Light of Fire",
    type: "Magic",
    slot: "",
    requirements: "10 INT, 2E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect: "Burn! Oh, Holy Llame!: Deal 2.25*MAG damage to one target.",
  },
  {
    name: "Light of Life",
    type: "Magic",
    slot: "",
    requirements: "10 INT, 3E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Restore! Oh, the divince providence!: Restore 1.5*MAG HP to all allies.",
  },
  {
    name: "Light of Holy",
    type: "Magic",
    slot: "",
    requirements: "10 INT, 1E",
    stats: {
      HP: 0,
      ATK: 0,
      DEF: 0,
      CRT: 0,
      CDM: 0,
      INT: 0,
      MAG: 0,
      RES: 0,
      INS: 0,
    },
    effect:
      "Cleanse! Oh the all of the sins!: Deal 1.5*MAG damage to one target and reduce self's INS by 2.",
  },
];

const importItemsToSupabase = async () => {
  try {
    console.log("Starting item import to Supabase...");

    // Insert items data into the 'items' table
    const { data, error } = await supabase.from("items").insert(itemsData);

    if (error) {
      console.error("Error importing items:", error);
      return { success: false, data };
    }

    console.log("Successfully imported items to Supabase!");
    return { success: true, data };
  } catch (err) {
    console.error("Exception occurred during import:", err);
    return { success: false, error: err };
  }
};

// Function to create the items table if it doesn't exist
const createItemsTable = async () => {
  try {
    // Check if the items table exists
    const { error: checkError } = await supabase
      .from("items")
      .select("name")
      .limit(1);

    // If the table exists, no need to create it
    if (!checkError) {
      console.log("Items table already exists");
      return { success: true };
    }

    console.log(
      "You need to create the items table in your Supabase dashboard"
    );
    console.log("Table structure should have columns for:");
    console.log("name, type, slot, requirements, stats, effect");
  } catch (err) {
    console.error("Error checking/creating table:", err);
    return { success: false, error: err };
  }
};

export { importItemsToSupabase, createItemsTable, itemsData };
